#! /bin/sh

if [ $# -ne 1 ]
then
	echo Usage: CreateLinuxCFile fileName
	exit 10
fi

sel="y"
if [ -e $1 ] 
then
	echo "File alreay exist, still Create it(y/n):"
	read sel
fi

if [ "$sel" = "n" ] 
then
	echo "CreateFile Failed!"
	exit 10
fi

touch $1

{
	echo "#include <stdio.h>"
	echo "#include <stdlib.h>"
	echo ""
	echo "int main(int argc, char** argv)"
	echo "{"
	echo "    "
	echo "}"
} > $1

vim $1
