#! /bin/sh

if [ $# -ne 1 ]
then
	echo Usage: CreateLinuxCFileAndMakeFile fileName
	exit 10
fi

sel="y"
if [ -e $1 ] 
then
	echo "File alreay exist, still Create it(y/n):"
	read sel
fi

if [ "$sel" = "n" ] 
then
	echo "CreateFile Failed!"
	exit 10
fi

filename=$1
makefilename="makefile"

touch $makefilename

objectname=${filename%%.*}
debugobjectname=${objectname}.o

{
	echo "$objectname : $filename"
	echo "		gcc $filename -o $objectname"
	echo "debug :"
	echo "		gcc -g $filename -o $debugobjectname"
	echo "clean :"
	echo "		rm *.o"
} > $makefilename

CreateLinuxCFile $filename
