#! /bin/sh

if [ $# -ne 1 ]
then
	echo Usage: CreatePythonScript fileName
	exit 10
fi

sel="y"
if [ -e $1 ] 
then
	echo "File alreay exist, still Create it(y/n):"
	read sel
fi

if [ "$sel" = "n" ] 
then
	echo "CreateFile Failed!"
	exit 10
fi

touch $1

{
	echo "import web"
	echo ""
	echo "urls = ('/', 'echo')"
	echo ""
	echo "class echo:"
	echo "    def GET(self):"
	echo "        return 'hello'"
	echo ""
	echo "app = web.application(urls, globals())"
	echo ""
	echo "if __name__ == '__main__':"
	echo "    app.run()"
} > $1

chmod +x $1
