#! /bin/sh

if [ $# -ne 1 ]
then
	echo Usage: CreatePythonScript fileName
	exit 10
fi

sel="y"
if [ -e $1 ] 
then
	echo "File alreay exist, still Create it(y/n):"
	read sel
fi

if [ "$sel" = "n" ] 
then
	echo "CreateFile Failed!"
	exit 10
fi

touch $1

{
	echo "#! /usr/bin/python"
	echo "# coding: utf-8"
	echo ""
	echo "# $1: Version 1"
	echo ""
	echo "def main():"
	echo "    "
	echo ""
	echo "if __name__ == '__main__':"
	echo "    main()"
} > $1

chmod +x $1
