#! /bin/sh

if [ $# -ne 1 ]
then
	echo Usage: CreatePythonScript fileName
	exit 10
fi

filename=$1
makefilename="makefile"

sel="y"
if [ -e $makefile ] 
then
	echo "File alreay exist, still Create it(y/n):"
	read sel
fi

if [ "$sel" = "n" ] 
then
	echo "CreateFile Failed!"
	exit 10
fi

touch $makefilename

objectname=${filename%%.*}

{
	echo "$objectname : $filename"
	echo "		gcc $filename -o $objectname"
	echo "clean :"
	echo "		rm *.o"
} > $makefilename

