#! /bin/sh

dirtoryname=$1
mkdir $dirtoryname

cd $dirtoryname

tempdir="templates"
mkdir $tempdir

src_name=$1.py

CreatePythonScript $src_name 
CreatePythonScript model.py 

sql="sql"
mkdir $sql
cd $sql
touch schema.sql
